import os
from keras.optimizer_v2.adam import Adam

EPOCHS = 200
BATCH_SIZE = 16
ROOT_DIR = os.getcwd()
OPT = Adam(lr=1e-4, decay=1e-4 / EPOCHS)
MODEL_PATH = "MODEL"
PLOT_PATH = "PLOT"
ACCURACY_PATH = "ACCURACY"
CLASSIFICATION_REPORT_PATH = "CLASSIFICATION_REPORT"
VALIDATION_REPORT_PATH = "VALIDATION_REPORT"
MODEL_SUMMARY_PATH = "MODEL_SUMMARY"
MONTAGES = "MONTAGES"
EVALUATION_REPORT = "EVALUATION_REPORT"
REPORT_PATH = "REPORT"
RESOURCE_PATH= "resources"
STATIC= "STATIC"


MODEL_VERSION_IN_WORK = "11"